### ISSUE TITLE
Not working on Spotify 1.1.64

### ISSUE THREAD

**Issue by yngsusboy** [khanhas/spicetify-cli#921]
## ℹ Computer information

- Spotify version: 1.1.64
- Spicetify version: 2.5.0

If i`m trying to load theme it showing blank spotify

**Comment by coniie** [comment]
I think I saw a different open issue on this topic about a week ago, but I still have the same problem after reinstalls.
![38667c7e337e73c6b470ab2cdc50083a (1)](https://user-images.githubusercontent.com/65280024/126719250-0d3fd05c-5581-4867-a47d-9476a1877899.png)

**Comment by saxobroko** [comment]
I'm getting this error during `spicetify apply`
```
spicetify v2.5.0
Overwriting raw assets:
OK
Transferring user.css:
OK
Applying additional modifications:
error Cannot find symbol for Custom app React symbols
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/khanhas/spicetify-cli/src/apply.insertCustomApp.func1(0xc000830000, 0x1aff61, 0x1aff61, 0xc000830000)
        D:/Code/spicetify-cli/src/apply/apply.go:180 +0xda6
github.com/khanhas/spicetify-cli/src/utils.ModifyFile(0xc00027cbc0, 0x38, 0xc0001a19d8)
        D:/Code/spicetify-cli/src/utils/utils.go:190 +0xdb
github.com/khanhas/spicetify-cli/src/apply.insertCustomApp(0xc00027cbc0, 0x38, 0xc000104240, 0x4, 0x4, 0xc0000a64a0, 0x2, 0x2, 0x101)
        D:/Code/spicetify-cli/src/apply/apply.go:155 +0x9e
github.com/khanhas/spicetify-cli/src/apply.AdditionalOptions(0xc0000c25a0, 0x2b, 0xc000104240, 0x4, 0x4, 0xc0000a64a0, 0x2, 0x2, 0x101)
        D:/Code/spicetify-cli/src/apply/apply.go:34 +0x484
github.com/khanhas/spicetify-cli/src/cmd.Apply(0x7f52d4, 0x5)
        D:/Code/spicetify-cli/src/cmd/apply.go:73 +0x598
main.main()
        D:/Code/spicetify-cli/spicetify.go:189 +0x519
```

**Comment by saxobroko** [comment]
Duplicate of #845
