### PR TITLE
Fix for Spotify 1.1.68

### LINKED ISSUE #1062: Lyrics-Plus continues to not work
## ℹ Computer information

- Spotify version: 1.1.68.628.geb44bd66
- Spicetify version: 2.6.3

## 📝 Provide detailed reproduction steps (if any)

1. load lyrics-plus page
2. something went wrong
3. reload page doesn't work

### ✔️ Expected result

_What is the expected result of the above steps?_
Page loads

### ❌ Actual result

_What is the actual result of the above steps?_
Page didn't load

## 📷 Screenshots

_Are there any useful screenshots?_
Screen Shot 2021-09-16 at 4 25 20 PM

### LINKED ISSUE #1076: spicetifyWrapper Uncaught TypeError
## ℹ Win10

- Spotify version: Spotify for Windows
1.1.68.628.geb44bd66
- Spicetify version: spicetify v2.6.4

## 📝 Provide detailed reproduction steps (if any)

1. apply Dribbblish Nord-dark theme
2. look at the console

### ✔️ Expected result
No errors
_What is the expected result of the above steps?_

### ❌ Actual result
```
Uncaught TypeError: Spicetify.Player.origin2.state.addProgressListener is not a function
    at waitOrigins (spicetifyWrapper.js:182)
    at r (vendor~xpui.js:1)
```
_What is the actual result of the above steps?_

## 📷 Screenshots
image

_Are there any useful screenshots?_

### PR DESCRIPTION
**Pull request by itsmeow**
Fixes #1076
Fixes #1062

# Fixes
- `Spicetify.ReactComponent.ContextMenu` and `Spicetify.ReactComponent.RightClickMenu` hooks (This fixes Lyrics Plus React minified error)
- Lyrics Plus progress issue
- Workaround for addProgressListener being removed
- Popup lyrics background being black (bug introduced in 116a5b4c9053b8c2287de139bf8e4f7ea3d9fadd)

### CODE REVIEW

**Review by afonsojramos — APPROVED** [review]
Looking good, thanks!
